
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dev_blog_development


test:
  <<: *default
  database: dev_blog_test

production:
  <<: *default
  database: dev_blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
